### ISSUE TITLE
Incompatibility with Reactors

### ISSUE THREAD

**Issue by Held03** [Kasperki/LogisticsUtility#12]
On Factorio 0.14.x, [LogisticSigns](https://mods.factorio.com/mods/Kasp3r/LogisticsSigns) (0.0.6) is incompatible with [Reactors](https://mods.factorio.com/mods/GotLag/Reactors) (1.6.0).
Both mods run well on there own. But if you have both mods in installed, Factorio crashes during loading.
The log just says:
```
 ...
 0.907 Loading mod core 0.0.0 (data.lua)
 0.913 Loading mod base 0.14.22 (data.lua)
 1.036 Loading mod LogisticsSigns 0.0.6 (data.lua)
 1.123 Loading mod Reactors 1.6.0 (data.lua)
 1.218 Loading mod LogisticsSigns 0.0.6 (data-final-fixes.lua)
 1.325 Checksum for core: 1291735968
 1.325 Checksum for mod base: 786624017
 1.325 Checksum for mod LogisticsSigns: 1929541944
 1.326 Checksum for mod Reactors: 1327236232
 1.850 Error Util.cpp:57: No such node (filename)
```
I'm not quite sure what the actual problem is or even hows fault it is (it might be even a Factorio bug).

**Comment by Kasperki** [comment]
This was fixed, closing.
