### ISSUE TITLE
Any plans to port this up to 0.15?

### ISSUE THREAD

**Issue by abordoli** [Kasperki/LogisticsUtility#14]
## For bug reports

- [ ] Check that you are using 0.12.X version of Factorio
- [ ] Check that you are using latest version of LogisticsUtility

* Explain your bug
* Steps how to reproduce
* Possible fix (Optional)

**Comment by Kasperki** [comment]
Hi,

I do not have time atm to update to 0.15.
I'll most propably update this straight to 0.16 when it's released.

**Comment by theRustyKnife** [comment]
Hi, I think I have a 0.15 port I made for myself laying around. I'll try to find it and send a PR if it works, but it'll have to wait till I get back from work...

**Comment by abordoli** [comment]
Awesome. No worries about doing it right away. I was just browsing through the mod archive and saw something that I'd use right away. Peace!

**Comment by Kasperki** [comment]
@theRustyKnife ported this succesfully to 0.15 big thanks to him!

**Comment by abordoli** [comment]
Thank you!
