### ISSUE TITLE
name problem and error

### ISSUE THREAD

**Issue by CraftYourWay** [Kasperki/LogisticsUtility#3]
hello, i have 2 problems.

first: when i download the file and put it in the mods folder it tells me the name is incorrect and missing _0.0.2 in the line.

second: i am getting this error: Error while running the event handler: _ _ LogisticsUtility_ _/control.lua:51:attemot to index field 'parent'(a nil value)

please fix :)

**Comment by Kasperki** [comment]
@CraftYourWay
Are you using latest version of factorio?

second: when does this error happen? What you do that you get this error.

**Comment by CraftYourWay** [comment]
im using version 0.12.29. and im clicking on a smart train stop from the mod smart trains

**Comment by Kasperki** [comment]
Most propably fixed in issue: https://github.com/Kasperki/LogisticsUtility/issues/6
