### ISSUE TITLE
[Logistics Signs] Error with (possibly) other mods with buttons in the upper left

### ISSUE THREAD

**Issue by bigyihsuan** [Kasperki/LogisticsUtility#6]
**List of relevant mods:**
- Belt Brush
- FAT Controller
- Foreman
- Blueprint String
  *Blueprint Flipper
- Mod Iconizer
- Advanced Logistics System
- Upgrade Planner
- Module Inserter

**Version of Logistics Signs:** 0.0.4
**Version of Factorio:** 0.12.34

If you click in the space in the upper left hand corner where all of the buttons for the mods listed above are, you get the following errors, and the game kicks me out of the save.
**Before installing Module Inserter:**

```
Error while running the event handler: __LogisticsSigns__/control.lua:73: attempt to index field 'parent' (a nil value)
```

**After installing Module Inserter:**

```
 Error while running the event handler: __LogisticsSigns__/control.lua:78: attempt to index field 'parent' (a nil value)
```

**Comment by bigyihsuan** [comment]
I can confirm that this bug does not occur when Logistic Signs is not installed.

**Comment by Kasperki** [comment]
@bigyihsuan thanks for reporting the issue! It should be now fixed in commit: https://github.com/Kasperki/LogisticsUtility/commit/0ea3d87b4168e375df9b05481abceeda50f98321
